[package]
name = "speakvim"
version = "0.1.0"
authors = ["Nicholas Young <hi@secretfader.com>"]
edition = "2018"

[dependencies]
deepspeech = "0.6.1"
cpal = "0.11.0"
structopt = "0.3.9"

[patch.crates-io]
cpal = { git = "https://github.com/RustAudio/cpal", branch = "master" }
